### PR TITLE
switch to using paradigm-highwinds

### PR DESCRIPTION
**Pull request by tom-james-watson**
Needs some testing

### CODE REVIEW

**Comment by tom-james-watson** [comment]
[Add `lastPurgedAt` to document when purge completes successfully.](https://trello.com/c/q0knSXDi/405-add-lastpurgedat-to-document-when-purge-completes-successfully)

**Comment by tom-james-watson** [comment]
[Only bust CDN cache for urls that need to be busted.](https://trello.com/c/FfHCFZc7/426-only-bust-cdn-cache-for-urls-that-need-to-be-busted)

**Comment by tom-james-watson** [comment]
[Confirm that I've setup the middleware cache bust as intended](https://trello.com/c/9lUsK4Mr/420-confirm-that-ive-setup-the-middleware-cache-bust-as-intended)

**Comment by chrisabrams** [comment]
👍

**Pull request merged**
